#sudo: false
language: perl
perl:
    - "5.14.4"
install:
    # install prereqs
    - "cpanm Moo"
    - "cpanm Date::Utility"
    - "cpanm Format::Util::Numbers"
    - "cpanm Array::Utils"
    - "cpanm Test::Perl::Critic"
    - "cpanm Math::Gauss::XS"
script:
    - "perl Makefile.PL && make test" 
