#sudo: false
language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
install:
    # install prereqs
    - "cpanm Test::Perl::Critic"
    - "cpanm Math::Gauss::XS"
    - "cpanm Math::BivariateCDF"
script:
    - "perl Makefile.PL && make test" 
