#sudo: false
matrix:
    fast_finish: true
language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
install:
    # install prereqs
    - "cpanm Test::FailWarnings"
    - "cpanm Test::Perl::Critic"
    - "cpanm Math::Gauss::XS"
    - "cpanm Math::BivariateCDF"
    - "cpanm Machine::Epsilon"
    - "cpanm -qn Test::Requires::Git"
    - "cpanm -qn Devel::Cover::Report::Codecov"
script:
    - "perl Makefile.PL && RELEASE_TESTING=1 make test"
after_success:
    - RELEASE_TESTING=1 cover -test -report codecov
