#sudo: false
language: perl
services:
    - redis-server
perl:
    - "5.14"
install:
    # install prereqs
    - "cpanm Moose"
    - "cpanm Date::Utility"
    - "cpanm Format::Util::Numbers"
    - "cpanm File::ShareDir"
    - "cpanm DateTime"
    - "cpanm Carp"
    - "cpanm feature"
    - "cpanm Path::Tiny"
    - "cpanm File::Basename"
    - "cpanm Template"
    - "cpanm Array::Utils"
    - "cpanm Text::CSV::Slurp"
    - "cpanm Scalar::Util"
    - "cpanm Test::Perl::Critic"
    - "cpanm MooseX::Singleton"
    - "cpanm YAML::CacheLoader"
    - "cpanm MIME::Base64"
    - "git clone https://60d764d753f8b0b231f5a4ee566d3eeaf5024cdc@github.com/regentmarkets/perl-Finance-Asset.git /tmp/perl-Finance-Asset"
    - "cd /tmp/perl-Finance-Asset && perl Makefile.PL && make install"
    - "git clone https://60d764d753f8b0b231f5a4ee566d3eeaf5024cdc@github.com/regentmarkets/perl-Feed-Listener.git /tmp/perl-Feed-Listener"
    - "cd /tmp/perl-Feed-Listener && perl Makefile.PL && make install"
    - "git clone https://60d764d753f8b0b231f5a4ee566d3eeaf5024cdc@github.com/binary-com/perl-FIX-Parser.git /tmp/perl-FIX-Parser"
    - "cd /tmp/perl-FIX-Parser && perl Makefile.PL && make install"
    - "ls"
    - "cd /home/travis/build/regentmarkets/perl-feed-panda"
script:
    - "sudo mkdir /feed"
    - "sudo mkdir /feed/panda"
    - "ls /"
    - "perl t/FixSimulator.pl &"
    - "perl Makefile.PL && make test" 
